name: pyavtrack360eval
channels:
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- pip=9.0.1=py36_1
- python=3.6.2=0
- setuptools=36.4.0=py36_1
- vc=14=0
- vs2015_runtime=14.0.25420=0
- wheel=0.29.0=py36_0
- wincertstore=0.2=py36_0
- pip:
  - cycler==0.10.0
  - matplotlib==2.1.2
  - numpy==1.14.1
  - pillow==5.0.0
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - pytz==2018.3
  - six==1.11.0
